# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - 3.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements_dev.txt

# Command to run tests, e.g. python setup.py test
script:
  - flake8 user_voting_rocks tests
  - python setup.py test